version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8023:80"
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.4-fpm
    volumes:
      - .:/code